### ISSUE TITLE
Improve indentation of function passed as argument

### ISSUE THREAD

**Issue by memeplex** [jalvesaq/R-Vim-runtime#1]
Instead of the pretty broken

```
sapply(1:10, function(i) {
       sapply(1:10, function(j) {
              c(i, j)
})
})
```

you should get something like

```
sapply(1:10, function(i) {
  sapply(1:10, function(j) {
    c(i, j)
  })
})
```

I think the rule could be simply stated as indent `<indent><anything>function(...)` as if it were just `<indent>function(...)`.

**Comment by jalvesaq** [comment]
Thanks for reporting the bug! Unfortunately, I think it is not so simple to fix, and I no longer have patience to spend time with the indent script, but we may let the issue open because someone else may want to write a pull request fixing it.

**Comment by jalvesaq** [comment]
@memeplex Please, see https://github.com/jalvesaq/R-Vim-runtime/pull/5
Although it is not the feature that you requested, it might be useful for this issue.

**Comment by jalvesaq** [comment]
Closing this issue because I'm no longer the maintainer of R runtime files...
