### ISSUE TITLE
Enable folding for rmarkdown files

### ISSUE THREAD

**Issue by jranke** [jalvesaq/R-Vim-runtime#12]
For me, it would be enough if it would fold the YAML header sections, and code chunks.

**Comment by jalvesaq** [comment]
Could you do a pull request for this, please? I don't use Rmarkdown.

**Comment by jranke** [comment]
I never wrote syntax folding commands, so I will not tackle this right now. Perhaps I will be able to do it at a later time.

**Comment by jranke** [comment]
@jalvesaq: I am wondering where syntax/pandoc.vim comes from that is mentioned in syntax/rmd.vim. I do not find such a file on my Debian system nor in current vim sources and I couldn't find anything in the Nvim-R documentation.

**Comment by jalvesaq** [comment]
I guess syntax/pandoc.vim (sourced at syntax/rmd.vim) is from [vim-pandoc-syntax](https://github.com/vim-pandoc/vim-pandoc-syntax) and ftplugin/pandoc.vim (sourced at ftplugin/rmd.vim) is from [vim-pandoc](https://github.com/vim-pandoc/vim-pandoc).

**Comment by jranke** [comment]
OK, thanks - this can be solved by installing vim-pandoc and vim-pandoc-syntax including commit pandoc-vim/pandoc-vim@29d6930 from vim-pandoc/vim-pandoc#192.
