### ISSUE TITLE
Problem with syntax highlighting (rnwoweb)

### ISSUE THREAD

**Issue by jdeut** [jalvesaq/R-Vim-runtime#13]
Latex keywords like `chapter`, `section` and `subsection` corrupt the highlighting of knitr chunks.

The following screenshots illustrate it.

![9 013](https://cloud.githubusercontent.com/assets/1739296/19597614/f114faee-9795-11e6-93e5-6f6c4808b818.png)

As soon as the full keyword is typed in (`subsection` in this case) all following chunks aren't highlighted as expected anylonger.

![9 014](https://cloud.githubusercontent.com/assets/1739296/19597618/f5825ce8-9795-11e6-95d8-2aac61ca08f7.png)

Unfortunately i have no idea how to fix it. It would be nice if anybody could fix this.

Best regards and thank you for your effort you are putting into all this

**Comment by jranke** [comment]
I could not reproduce this problem, neither with an old syntax/rnoweb.vim from Debian jessie, nor with the current version in this repository. Could you get the test file from [here](https://raw.githubusercontent.com/jranke/R-Vim-runtime/rnw_highlighting/tests/check_latex_keywords.rnw) and report back after checking your runtimepath `:set runtimepath` for suspicious entries?

**Comment by jdeut** [comment]
If I load `check_latex_keywords.rnw` into vim the syntax is highlighted correctly:

![9 017](https://cloud.githubusercontent.com/assets/1739296/19620617/927811d2-9881-11e6-8611-9c22b0d9cabc.png)

However if i delete the line that starts the `document` environment the syntax highlighting breaks

![9 018](https://cloud.githubusercontent.com/assets/1739296/19620630/f4044420-9881-11e6-8ba1-16880f1c44c0.png)

Can anybody reproduce this behavior?

Only for the case that somebody asks why i have no `document` environment in my file: I work on a large document using child documents.

Best regards

**Comment by jranke** [comment]
Yes, I can reproduce this. I noticed, however, that if you delete the documentclass declaration as well, the highlighting is OK again. When I was working on a large document with child documents in TeX, I used to start the child documents with \section{} or rather \chapter{}, if I recall correctly. Would this be an agreeable solution for you?

**Comment by jdeut** [comment]
> When I was working on a large document with child documents in TeX, I used to start the child documents with \section{} or rather \chapter{}, if I recall correctly. Would this be an agreeable solution for you? 

Yes, that would be an agreeable solution. Unfortunately there is something loaded by vim on my machine that breaks the highlighting anyways.

![9 019](https://cloud.githubusercontent.com/assets/1739296/19620840/5b03227e-9885-11e6-97d7-95541158feab.png)

Probably you can't reproduce the behavior with this text:

```

\chapter{Blabla}

<<Test>>=
  print("Hello world")
@

\section{}

<<Test_2>>=
  print("Hello again")
@
```

In the meantime i will dig deeper and i will let you know who the culprit is...

**Comment by jranke** [comment]
You are right, I can not reproduce this. On my machine, this is highlighted as expected. Good luck in your search!

**Comment by jdeut** [comment]
I have found the culprit. I wrote a custom `syntax/rnoweb.vim` file sometime. This file obviously interfered with the offical `syntax/rnoweb.vim`. I removed it and everything work as expected now.

Anyhow thanks for your feedback...

**Comment by jranke** [comment]
You're welcome. Good to know that it works now.
