### ISSUE TITLE
Flexdashboard style Rmd file syntax highlighting

### ISSUE THREAD

**Issue by jarodmeng** [jalvesaq/R-Vim-runtime#23]
It seems that Rmd syntax highlighting doesn't work well with [Flexdashboard](https://github.com/rstudio/flexdashboard) files. The yaml setting separator on top seems to confuse the syntax highlighter

The file I opened here is in the flexdashboard package's `inst/examples/crandash` folder.

![Rmd screenshot](http://i.imgur.com/Z9WYPm2.png)

**Comment by jalvesaq** [comment]
It works here:
![screenshot from 2017-08-26 11-48-43](https://user-images.githubusercontent.com/891655/29742381-a23f4af2-8a54-11e7-9d6a-7892400e3263.png)

**Comment by jarodmeng** [comment]
It seems to be related to [vim-markdown](https://github.com/plasticboy/vim-markdown). Once I disable it, the syntax highlighting seems to work. I will investigate a bit more to see what's the root cause. Thanks!

**Comment by jalvesaq** [comment]
I mostly rewrote the syntax/rmd.vim script. I believe that it now interacts well with [zotcite](https://github.com/jalvesaq/zotcite), [vim-pandoc-syntax](https://github.com/vim-pandoc/vim-pandoc-syntax) and [gabrielelana/vim-markdown](https://github.com/gabrielelana/vim-markdown), but not with [plasticboy/vim-markdown](https://github.com/plasticboy/vim-markdown).

**Comment by jalvesaq** [comment]
I tried the plasticboy/vim-markdown plugin again and couldn't see the bug anymore. It might have been fixed...
