### ISSUE TITLE
Respect `cindent` `mN` alignment rule

### ISSUE THREAD

**Issue by ashiklom** [jalvesaq/R-Vim-runtime#24]
The RStudio way of indenting code is like this:

```r
x <- list(
  a = 3,
  b = 1:5,
  c = "hello"
)
```

This _should_ be achievable by setting `g:r_indent_align_args = 0` and `set cinoptions = (0,W2,m1`. However, this combination produces the following:

```r
x <- list(
  a = 3,
  b = 1:5,
  c = "hello"
  )  # <--- This parenthesis should be aligned with `x` per the `m1` cindent option
```

Is there a way to make vim respect the `m1` cindent option, at least when `g:r_indent_align_args = 0`?

**Comment by ashiklom** [comment]
I haven't done extensive testing, but it seems like something like this in the `GetRIndent()` function does the trick:

```vim
  " Unindent a closing parenthesis. For example:
  " list(
  "   a = 5,
  "   b = 8
  " ) <--- Line this up with the beginning of `list`
  if cline =~ '^\s*)'
    let indline = s:Get_matching_brace(clnum, '(', ')', 1)
    return indent(indline)
  endif

```

This also requires adding `0)` to the `indentkeys` at the top of the indent file.

**Comment by jalvesaq** [comment]
The procedure that I follow to test changes in `indent/r.vim` is:

  - Make a copy of both `tests/indent_test_noalign.R` and `tests/indent_test.R` into `/tmp`.
  - In both files at the `/tmp` directory do in normal mode `gg=G` to indent the whole buffer, save it and quit Vim/Neovim. (But do this after setting the options in your `vimrc` as described at the top of the files)
  - Check the differences between the newly indented files and the original ones:
```
    nvim -d /path/to/R-Vim-runtime/tests/indent_test_noalign.R indent_test_noalign.R
    nvim -d /path/to/R-Vim-runtime/tests/indent_test.R indent_test.R
```
In both cases, the changes in `indent/r.vim` should improve the indentation without introducing any new bug.

**Comment by jalvesaq** [comment]
Actually, your suggestion fixes the issue without introducing any new bug. I'm sorry for not testing it earlier.
