### ISSUE TITLE
Comment string value wrong for rmd?

### ISSUE THREAD

**Issue by zippeurfou** [jalvesaq/R-Vim-runtime#25]
it is set to `>` (https://github.com/jalvesaq/R-Vim-runtime/blob/master/ftplugin/rmd.vim#L25)
but I fail to understand why. Code comments in R should be `#` as far as I understand.

**Comment by jalvesaq** [comment]
The comment string in R is `#`, and there is no comment string in Markdown. Vim's documentation says that the option `commentstring` is "only used to add markers for folding", but actually it is also used when formatting a paragraph with the Normal mode command `gqap`. Please, see:
```
:h gaqp
:h fo-table
```
Altough `>` is not a comment string, it is a quotation prefix and `commentstring=> %s` ensures that quotation paragraphs are properly formatted by the `gqap` command. Unfortunately, we can't have both `>` as comment string for Markdown and `#` for R in the same RMarkdown buffer. So, we have to choose what to get properly formatted, R comments or Markdown quotations. Currently, `ftplugin/rmd.vim` follows Markdown, not R. We can make this behavior optional, but a really decent solution would be to set `formatexpr`.

**Comment by jalvesaq** [comment]
I was wrong. The option `comments` is important for the `gqap` command, not `commentstring`.

**Comment by jalvesaq** [comment]
The 'commentstring' option in Rmd and in Markdown are the same. I think it should be empty because Markdown doesn't have a comment string, but I'm not sure.

@zippeurfou Could you please explain what would change if 'commentstring' was set to `#`?

**Comment by zippeurfou** [comment]
I just use `tpope/vim-commentary` that uses `commentstring` and like to use the shortcut from the pluging that is `gcc` to comment my code. Usually I only need to comment R code in my rmarkdown file. That's why I was suggesting to use `#` instead as a normal R file comments. I had no idea that it was so much more complex 😨

**Comment by jalvesaq** [comment]
Markdown does not have a comment string; R does. So, I think it makes sense to have `#` as 'commentstring' in RMardown, as you suggest.
