### ISSUE TITLE
Roxygen highlighting kicks in for some trailing line comments

### ISSUE THREAD

**Issue by kevinushey** [jalvesaq/R-Vim-runtime#26]
I noticed that Roxygen (?) syntax highlighting will kick in for trailing comments in some situations. For example:

```R
c(
  'a', #'b', 'c'
)
```

This highlights as:

![screen shot 2018-02-15 at 3 00 44 pm](https://user-images.githubusercontent.com/1976582/36285590-064f2122-1261-11e8-9bb0-828611352465.png)

Note that because `#'` gets consumed as a single token token, it seems to mess up the rest of the highlighting as well.

**Comment by jalvesaq** [comment]
Perhaps either @jranke or @klmr could help in this issue (I don't use ROxygen).

**Comment by jranke** [comment]
Hi Kevin,

nice to see an Rstudio developer using vim, or at least the vim runtime :)

Johannes

**Comment by kevinushey** [comment]
Thank you for the quick fix!

In fact, we have a few heavy Vim users on the RStudio IDE team, so we too owe you a debt of gratitude for maintaining the R runtime support in Vim :-)
