### ISSUE TITLE
About "/R-Vim-runtime/syntax/rmd.vim"

### ISSUE THREAD

**Issue by yuntas** [jalvesaq/R-Vim-runtime#3]
Hi, Mr.jalvesaq.

Thanks for creating program about Rmd syntax highlighting.

I discovered when I wanna do syntax highlight Rmd files.

So, I downloaded "rmd.vim", and 'mv rmd.vim /usr/share/vim/vim74/syntax/'.

But, I was able to do syntax highlight Rmd files.

please teach me.

**Comment by jalvesaq** [comment]
Perhaps you need this other file too:
https://github.com/jcfaria/Vim-R-plugin/blob/master/ftdetect/r.vim
You may try to copy it to `~/.vim/ftdetect/`

**Comment by kynan** [comment]
@jalvesaq I came across the same issue and added the corresponding `autocmd` to my `~/.vimrc` manually. Shouldn't the ftdetect component of Vim-R-plugin not be part of this repository (since syntax etc. is defined here)?

**Comment by jalvesaq** [comment]
I think that the appropriate place is the Vim-R-plugin because I see
ftdetect as a complement to the ftplugin directory, but there is no harm if
we duplicate it in this repository.

**Comment by jalvesaq** [comment]
I added the ftdetect file: https://github.com/jalvesaq/R-Vim-runtime/commit/fc10b2543bc2830f3b544ed497ee0e52f5e96899

**Comment by kynan** [comment]
Great, thanks!
