### ISSUE TITLE
Syntax highlight bug after a single quote

### ISSUE THREAD

**Issue by hongyuanjia** [jalvesaq/R-Vim-runtime#33]
Thanks for this great plugin.

I found a syntax highlight bug that whenever there is a single quote, all text after that will be highlighted as quoted text. Please see blow:

![2018-08-25-233830_858x217_scrot](https://user-images.githubusercontent.com/20545387/44619995-1f78d580-a8c0-11e8-9dbd-04f2beb5d329.png)

**Comment by jalvesaq** [comment]
Thanks for reporting the issue. It should be fixed in a minute.

**Comment by hongyuanjia** [comment]
I can confirm that it has been fixed. Thanks!
