### ISSUE TITLE
Rmd syntax error when "g:markdown_fenced_languages" is set

### ISSUE THREAD

**Issue by michaelmalick** [jalvesaq/R-Vim-runtime#35]
When the `g:markdown_fenced_languages` variable is set (a variable used by the default markdown syntax file), opening an Rmd file causes an error: `E119: Not enough arguments for function: substitute`. I can produce the error using the below minimal .vimrc and opening a `*.rmd` file.

```
set nocompatible
syntax enable
filetype plugin on
filetype indent on
let g:markdown_fenced_languages = ['r', 'bash=sh']
```

**Comment by jalvesaq** [comment]
Thanks for reporting the bug!
I'm going to commit the fix now.
