### ISSUE TITLE
Highlighting of roxygen for R6 documentation broken

### ISSUE THREAD

**Issue by mllg** [jalvesaq/R-Vim-runtime#36]
With the release of roxygen2-7.0.0, there is now support for documenting R6 classes (see https://cran.r-project.org/web/packages/roxygen2/vignettes/rd.html, section R6). 

Syntax is broken for intended roxygen blocks (those which document fields or methods). Example from the vignette below:

```r
#' R6 Class Representing a Person
#'
#' @description
#' A person has a name and a hair color.
#'
#' @details
#' A person can also greet you.

Person <- R6::R6Class("Person",
public = list(

    #' @field name First or full name of the person.
    name = NULL,

    #' @field hair Hair color of the person.
    hair = NULL,

    #' @description
    #' Create a new person object.
    #' @param name Name.
    #' @param hair Hair color.
    #' @return A new `Person` object.
    initialize = function(name = NA, hair = NA) {
      self$name <- name
      self$hair <- hair
      self$greet()
    },

    #' @description
    #' Change hair color.
    #' @param val New hair color.
    #' @examples
    #' P <- Person("Ann", "black")
    #' P$hair
    #' P$set_hair("red")
    #' P$hair
    set_hair = function(val) {
      self$hair <- val
    },

    #' @description
    #' Say hi.
    greet = function() {
      cat(paste0("Hello, my name is ", self$name, ".\n"))
    }
  )
)

```

**Comment by jalvesaq** [comment]
@jranke, could you, please, look at this issue?

**Comment by jranke** [comment]
yes, I do intend to look into this - so far I haven't used this nice roxygen 
feature yet, but I do have some roxygen documentation for R6 classes, so I 
will get to it eventually at some point. But I do not know if I will succeed, 
it looks a bit difficult to me. If anyone wants to step in meanwhile ...
