### ISSUE TITLE
Highlighting for Rmd but not for Rnw

### ISSUE THREAD

**Issue by xllvrr** [jalvesaq/R-Vim-runtime#39]
Would there be any reason why the highlighting would appear for Rmd files but not Rnw files? I'm using vim-tex as a plugin, but it doesn't seem to interfere with the highlighting, so I don't know why the chunks aren't getting highlighted.

**Comment by jranke** [comment]
Just a shot in the dark: Could it be that you have installed vim-pandoc-syntax, but not R-Vim-runtime?

**Comment by xllvrr** [comment]
Unfortunately I have installed R-Vim-runtime. I also tried copying the rnoweb.vim to the global syntax, local syntax and not at all, but none of those work.

If neither Rmd or Rnw were working it would be easier to look for things, but only Rnw doesn't work. Notably I have vim-pandoc-syntax, but commenting that out does not deactivate the highlighting for Rmd so I ruled that out as well.

**Comment by jranke** [comment]
Is the filetype of the Rnw files correctly set to rnw as shown by the command below

```
:set ft
```

**Comment by xllvrr** [comment]
The files are set to rnoweb, as per the syntax in R-Vim-runtime. Let me try rnw and see whether that changes anything.

**Comment by xllvrr** [comment]
Update: Setting to rnw disables all highlighting

**Comment by jranke** [comment]
Sorry, I mislead you with rnw... It should of course be rnoweb.

Can you show an example chunk that is not highlighted?

**Comment by xllvrr** [comment]
So in trying to demonstrate the situation, I found something quirky. If I have no parameters set (or have commented them out), the highlighting works.

![Highlighting True](https://user-images.githubusercontent.com/35357732/74428440-f709e000-4e93-11ea-8456-806c02fd851c.png)

However, the moment I add some Latex settings or uncomment them, the highlighting for R code vanishes

![Highlighting False](https://user-images.githubusercontent.com/35357732/74428477-0721bf80-4e94-11ea-8b29-5fd503b6ea5a.png)

And I completely can't explain why

**Comment by jranke** [comment]
There  is an unmatched opening brace at the beginning of the renewcommand line...

**Comment by xllvrr** [comment]
I completely did NOT see that. I'm an idiot. Thank you for your assistance!

**Comment by jranke** [comment]
> I completely did NOT see that. I'm an idiot. Thank you for your assistance!
No, you are surely not an idiot! Anyway, glad I could help. Cheers, Johannes
