### ISSUE TITLE
Syntax highlighting for raw (literal) strings in R≥4.0.0

### ISSUE THREAD

**Issue by wtraylor** [jalvesaq/R-Vim-runtime#42]
R 4.0.0 [brings](https://stat.ethz.ch/pipermail/r-announce/2020/000653.html) a new notation for raw strings:
> There is a new syntax for specifying _raw_ character constants
      similar to the one used in C++: r"(...)" with ... any character
      sequence not containing the sequence )".  This makes it easier to
      write strings that contain backslashes or both single and double
      quotes.

Therefore, the `\d` in the following code snippet should not be highlighted as an error:
```R
regex <- r"(\d)"
```

Versions used:
- [syntax/r.vim](https://github.com/jalvesaq/R-Vim-runtime/blob/master/syntax/r.vim) in commit a9b6ac04a9aea0a369f5e52a9475c71e4ad6adf4.
- Neovim v0.4.3
- Archlinux
- R 4.0.1

**Comment by jalvesaq** [comment]
I'm sorry for the long delay, but I believe the issue is fixed now.

**Comment by wtraylor** [comment]
Yes, I can confirm that it’s fixed. Thanks a lot!
