### ISSUE TITLE
Wrong indentation after magrittr pipe `%>%`

### ISSUE THREAD

**Issue by pchabros** [jalvesaq/R-Vim-runtime#53]
Here's what I get with `%>%`:

```r
mtcars %>%
  filter(
  mpg > 10
)
```

Also after auto-indenting above code with `==` I get:

```r
mtcars %>%
filter(
  mpg > 10
)
```

For native pipe `|>` it works as expected:

```r
mtcars |>
  filter(
    mpg > 10
  )
```

I tried to play with `r_indent_align_args` and `r_indent_ess_compatible` but without any effect.
Unfortunately I'm not sure when exactly it broke (it was working well some time ago), but I think after updating NeoVim to `0.8.0`.
Maybe it's only something on my side. Just let me know if you can reproduce, if not I'll close the issue.

Thank you in advance!

**Comment by jalvesaq** [comment]
I get exactly the same result with both `%>%`  and `|>` (Vim 9.0, Neovim 0.9). As I type, I get the following indentation ('shiftwidth' = 4):

```r
mtcars |>
    filter(
           mpg > 10
           )
```

With the normal mode command `ggG=`, I get:

```r
mtcars |>
    filter(
           mpg > 10
    )
```
