### ISSUE TITLE
Indentation issue with `ggplot()` if function spans multiple lines

### ISSUE THREAD

**Issue by PMassicotte** [jalvesaq/R-Vim-runtime#55]
First, thank you. Yesterday you pointed me toward my treesitter config causing problems with indenting lines ending with `+` when creating a plot. For the most part, it now works fine. I am just facing one more issue when the arguments of a function are spread across multiple lines, then the indentation is not working anymore.

https://github.com/jalvesaq/R-Vim-runtime/assets/4519221/f3315188-6e43-443a-b255-70814c36de62

Any ideas?

**Comment by jalvesaq** [comment]
It might have been fixed by the last commit, but I only tested it with a simple example.

**Comment by PMassicotte** [comment]
oh nice, forks fine except if the `+` is added on the last layer of a plot (ie. the indentation works perfectly if I do it in between:

```r
mtcars |>
  ggplot() +
  geom_histogram(
    data = mtcars
  ) + <------------ this now work perfectly
  labs(
    title = "title"
  )  + <--------- The next line will not be indented correctly
```

Thank you very much!

**Comment by jalvesaq** [comment]
Support for a code style with closing parenthesis alone in its own line is not a priority. There is support only for curly braces in this case. Anyway, I consider the code above to be reasonably well-indented. The indentation that I get is:

With `r_indent_align=1`:

```r
mtcars |>
    ggplot() +
    geom_histogram(
                   data = mtcars
                   ) +
    labs(
         title = "title"
         ) + 
    xlab()
```
And with `r_indent_align=0`: 

```r
mtcars |>
    ggplot() +
    geom_histogram(
        data = mtcars
        ) +
    labs(
        title = "title"
        ) + 
    xlab()
```

**Comment by PMassicotte** [comment]
With this morning's update of `R-Vim-runtime`, I am facing the same issue as yesterday. 

![Peek 2023-10-08 08-32](https://github.com/jalvesaq/R-Vim-runtime/assets/4519221/bac13260-3e72-4a3f-a25a-7c70f05bb8dd)

I understand that might not be an easy fix, so feel free to close the issue.

Thank you for your work,
Phil

**Comment by jalvesaq** [comment]
After adding `vim.o.autoindent = false` to my `init.lua`, I finally could replicate the issue. It should be fixed now.

**Comment by PMassicotte** [comment]
Thank you!

**Comment by PMassicotte** [comment]
I am sorry to post again, but I have noticed that the indentation is not working properly if the closing parenthesis is aligned with the function:

```r
mtcars |>
  ggplot(aes(x = hp)) +
  geom_histogram(
    bins = 10
  ) + <--- if I press enter here, the next line will not be aligned properly
  
 mtcars |>
  ggplot(aes(x = hp)) +
  geom_histogram(
    bins = 10
    ) + <--- if I press enter here, the next line will be aligned properly
```

![Peek 2023-10-10 08-27](https://github.com/jalvesaq/R-Vim-runtime/assets/4519221/38c08ff2-7322-402e-9c7d-8155e032b415)

**Comment by jalvesaq** [comment]
As I have told:

> Support for a code style with closing parenthesis alone in its own line is not a priority. There is support only for curly braces in this case.

If you don't move the parenthesis, the indentation of the next line is correct. I agree with you that the code would be prettier if the closing parenthesis were indented as closing braces are. However, the most important thing is that the indentation is correct in the next line, that is, all the lines below it will be correctly indented. This is the priority.

I'm sorry, but it's too complicated to fix something without breaking something else in the `indent/r.vim` script. I will accept a pull request if someone can enhance the code keeping the first 622 lines of [indent_test.R](https://github.com/jalvesaq/R-Vim-runtime/blob/master/tests/indent_test.R) and the first 613 lines of [check_noalign.sh](https://github.com/jalvesaq/R-Vim-runtime/blob/master/tests/check_noalign.sh) correctly indented. Please, run the scripts [check_align.sh](https://github.com/jalvesaq/R-Vim-runtime/blob/master/tests/check_align.sh) and [check_noalign.sh](https://github.com/jalvesaq/R-Vim-runtime/blob/master/tests/check_noalign.sh) to see what I mean.

**Comment by PMassicotte** [comment]
Thank you, I will try to give it a try, maybe I can come with something.

I noticed that it works with the `|>` operator, 

![Peek 2023-10-10 12-21](https://github.com/jalvesaq/R-Vim-runtime/assets/4519221/c4aa5be0-fb09-494f-97a9-7f2974943a20)

I guess that all the logic is in https://github.com/jalvesaq/R-Vim-runtime/blob/master/indent/r.vim?

**Comment by jalvesaq** [comment]
Yes, it's all there.
