### ISSUE TITLE
R-Vim-runtime

### ISSUE THREAD

**Issue by stegzzz** [jalvesaq/R-Vim-runtime#7]
I am getting the message about outdated runtime which refers me to https://github.com/jalvesaq/R-Vim-runtime where it states "Note that the R-Vim-runtime files must be sourced before the Vim-R-plugin files, that is, if you still receive the warning about outdated runtime after installing these files, try changing the order of Vim-R-plugin and R-Vim-runtime."

Please can you explain how to change the order of sourcing?

Thanks, stegzzz

**Comment by jalvesaq** [comment]
It seems that each system sources the runtime files in a different order.

I do not have the R-Vim-runtime directory in my 'runtimepath'. When I am testing the R-Vim-runtime files, I copy them to both /usr/local/share/vim/vim74 and /usr/local/share/nvim/runtime because this is guaranteed to work.

Below is an example of how to change the order of sourcing (using [vim-plug](https://github.com/junegunn/vim-plug)):

Attempt 1:

```
    Plug 'jalvesaq/Nvim-R'
    Plug 'jalvesaq/R-Vim-runtime'
```

Attempt 2:

```
    Plug 'jalvesaq/R-Vim-runtime'
    Plug 'jalvesaq/Nvim-R'
```

However, I can't guarantee that either of the two attempts above will work.

**Comment by stegzzz** [comment]
Thanks for looking at this. I checked some things. First, I have the 'fix' files from: https://github.com/jcfaria/Vim-R-plugin/commit/9ecae8c1d5b6c8d646dddf87f46087986ebab3e3

Second, :scriptnames suggests that the Vim-R-plugin files are being loaded before the R-Vim-runtime files with the possible exception of ftdetect\r.vim (see listing below, created right after an r script was loaded and the warning about out of date runtime). The Vim-R-plugin files are not loaded until an r script is loaded. 

Third, I installed plug and put the following in _vimrc:

call plug#begin('c:\program files (x86)\vim\vimfiles\autoload')
Plug 'c:\program files (x86)\vim\vimfiles\autoload'
Plug 'c:\program files (x86)\vim\vimfiles\doc'
Plug 'c:\program files (x86)\vim\vimfiles\ftdetect'
Plug 'c:\program files (x86)\vim\vimfiles\ftplugin'
Plug 'c:\program files (x86)\vim\vimfiles\r-plugin'
Plug 'c:\program files (x86)\vim\vimfiles\syntax'
call plug#end()

According to what I understand this should load the Vim-R-plugin files (which are in autoload, doc, ftdetect, ftplugin, and r-plugin) but I can't find the  R-Vim-runtime files on my system, so I'm not sure how to source them first. I guess they must be there somewhere because, apart from the out-of-date message, everything seems to be working properly.

Maybe I'm completely misunderstanding things but if you can offer some help that would be great.

Thanks, stegzzz

:scriptnames
  1: C:\Program Files (x86)\Vim_vimrc
  2: C:\Program Files (x86)\Vim\vim74\syntax\syntax.vim
  3: C:\Program Files (x86)\Vim\vim74\syntax\synload.vim
  4: C:\Program Files (x86)\Vim\vim74\syntax\syncolor.vim
  5: C:\Program Files (x86)\Vim\vim74\filetype.vim
  6: C:\Program Files (x86)\Vim\vimfiles\ftdetect\r.vim
  7: C:\Program Files (x86)\Vim\vim74\ftplugin.vim
  8: C:\Program Files (x86)\Vim\vim74\indent.vim
  9: C:\Program Files (x86)\Vim\vim74\vimrc_example.vim
 10: C:\Program Files (x86)\Vim\vim74\syntax\nosyntax.vim
 11: C:\Program Files (x86)\Vim\vim74\mswin.vim
 12: C:\Program Files (x86)\Vim\vim74\autoload\paste.vim
 13: C:\Program Files (x86)\Vim\vim74\plugin\getscriptPlugin.vim
 14: C:\Program Files (x86)\Vim\vim74\plugin\gzip.vim
 15: C:\Program Files (x86)\Vim\vim74\plugin\matchparen.vim
 16: C:\Program Files (x86)\Vim\vim74\plugin\netrwPlugin.vim
 17: C:\Program Files (x86)\Vim\vim74\plugin\rrhelper.vim
 18: C:\Program Files (x86)\Vim\vim74\plugin\spellfile.vim
 19: C:\Program Files (x86)\Vim\vim74\plugin\tarPlugin.vim
 20: C:\Program Files (x86)\Vim\vim74\plugin\tohtml.vim
 21: C:\Program Files (x86)\Vim\vim74\plugin\vimballPlugin.vim
 22: C:\Program Files (x86)\Vim\vim74\plugin\zipPlugin.vim
 23: ~\documents\vims\E172.vim
 24: C:\Program Files (x86)\Vim\vim74\scripts.vim
 25: C:\Program Files (x86)\Vim\vimfiles\ftplugin\r_rplugin.vim
 26: C:\Program Files (x86)\Vim\vimfiles\r-plugin\common_global.vim
 27: C:\Program Files (x86)\Vim\vimfiles\r-plugin\setcompldir.vim
 28: C:\Program Files (x86)\Vim\vimfiles\r-plugin\windows.vim
 29: C:\Program Files (x86)\Vim\vimfiles\r-plugin\common_buffer.vim
 30: C:\Program Files (x86)\Vim\vim74\indent\r.vim
 31: C:\Program Files (x86)\Vim\vim74\syntax\r.vim
 32: C:\Program Files (x86)\Vim\vimfiles\r-plugin\functions.vim
 33: ~\AppData\Roaming\Vim-R-plugin\fun_base_3.2.2
 34: ~\AppData\Roaming\Vim-R-plugin\fun_stats_3.2.2
 35: ~\AppData\Roaming\Vim-R-plugin\fun_graphics_3.2.2
 36: ~\AppData\Roaming\Vim-R-plugin\fun_grDevices_3.2.2
 37: ~\AppData\Roaming\Vim-R-plugin\fun_utils_3.2.2
 38: ~\AppData\Roaming\Vim-R-plugin\fun_methods_3.2.2

R-Vim-runtime files listed at: https://github.com/jalvesaq/R-Vim-runtime
    ftdetect/r_file_types.vim
    ftplugin/r.vim
    ftplugin/rhelp.vim
    ftplugin/rmd.vim
    ftplugin/rnoweb.vim
    ftplugin/rrst.vim
    indent/r.vim
    indent/rhelp.vim
    indent/rmd.vim
    indent/rnoweb.vim
    indent/rrst.vim
    syntax/r.vim
    syntax/rhelp.vim
    syntax/rmd.vim
    syntax/rrst.vim

Vim-R-plugin files listed at: http://www.lepem.ufc.br/jaa/r-plugin.html#r-plugin-files
   autoload/rcomplete.vim
   doc/r-plugin.txt
   ftdetect/r.vim
   ftplugin/r_rplugin.vim
   ftplugin/rbrowser.vim
   ftplugin/rdoc.vim
   ftplugin/rhelp_rplugin.vim
   ftplugin/rmd_rplugin.vim
   ftplugin/rnoweb_rplugin.vim
   ftplugin/rrst_rplugin.vim
   r-plugin/common_buffer.vim
   r-plugin/common_global.vim
   r-plugin/functions.vim
   r-plugin/gui_running.vim
   r-plugin/osx.vim
   r-plugin/r.snippets
   r-plugin/rmd.snippets
   r-plugin/setcompldir.vim
   r-plugin/synctex_evince_backward.py
   r-plugin/synctex_evince_forward.py
   r-plugin/windows.vim
   syntax/rbrowser.vim
   syntax/rdoc.vim
   syntax/rout.vim

**Comment by jalvesaq** [comment]
Perhaps someone else know how to make your Vim source the files from `R-Vim-runtime` before sourcing the files from `C:\Program Files (x86)\Vim\vimfiles`. Unfortunately, I don't know how to do that. I can think in only two alternative:
1. Follow the instruction from http://www.vim.org/download.php#pc and Install "Vim without cream".
2. Copy the files from `R-Vim-runtime` to `C:\Program Files (x86)\Vim\vimfiles`.

In either case you will get up to date runtime files in a place where it is guaranteed that they will be sourced.

**Comment by jalvesaq** [comment]
I'm not sure if this issue still is relevant. Maybe we could close it...

**Comment by stegzzz** [comment]
Sure, this was a long time ago and my system is working well. Unfortunately
I can't help with a solution as I basically changed everything, rebuilt vim
updated etc. Thanks for asking though.

BW, Steve

**Comment by jalvesaq** [comment]
Thanks for the feedback!
